### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by M3nin0** [augustoliks/supervisord-fastapi#1]
Talvez seria legal considerar a utilização dos `Namespaces`, ao invés da importação direta dos componentes de cada biblioteca.

Isto causaria mudanças como a apresentada abaixo no código:

```python
from pathlib import Path
from typing import List
```

É trocado por

```python
import pathlib
import typing
```

Esta pequena mudança, no momento da utilização dos componentes de cada biblioteca utilizada torna claro o local de onde tal componente está vindo, como eu apresento abaixo.

```python
pathlib.Path
typing.List
```

É uma pequena sugestão que com o aumento de bibliotecas pode ser útil para manter o código legível, mesmo que apresente um pouco mais de código.

O projeto está legal =D

**Comment by augustoliks** [comment]
Muito obrigado pelo feedback :rocket: 

Levei em conta a sugestão na ultima versão disponível na `main`.
